
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sat Jun 26 14:31:58 MDT 2021
//----------------------------------------------------

package codigo;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int Mayor_que = 62;
  public static final int Parentesis_c = 68;
  public static final int Parentesis_a = 67;
  public static final int Signo_Agrupacion = 57;
  public static final int Operador_relacional = 58;
  public static final int Menos = 45;
  public static final int Musica = 29;
  public static final int Humedad = 11;
  public static final int Corchete_c = 72;
  public static final int Rutina = 9;
  public static final int Corchete_a = 71;
  public static final int Tipo = 47;
  public static final int Comenzar = 6;
  public static final int Fertilizante = 34;
  public static final int Comprobar = 8;
  public static final int Llaves_c = 70;
  public static final int Llaves_a = 69;
  public static final int Sector = 46;
  public static final int Volumen = 28;
  public static final int Mas = 44;
  public static final int Resta = 49;
  public static final int Maximo = 25;
  public static final int Pausar = 31;
  public static final int Luminosidad = 13;
  public static final int Complemento = 16;
  public static final int Suma = 48;
  public static final int ERROR = 73;
  public static final int Iniciar = 3;
  public static final int Repetir = 40;
  public static final int Reproducir = 55;
  public static final int Posicion = 32;
  public static final int Terminar = 7;
  public static final int Durante = 17;
  public static final int Incrementar = 26;
  public static final int COMA = 54;
  public static final int Grados = 21;
  public static final int ERROR7 = 79;
  public static final int Op_aritmeticos = 56;
  public static final int ERROR6 = 78;
  public static final int ERROR5 = 77;
  public static final int ERROR4 = 76;
  public static final int ERROR3 = 75;
  public static final int ERROR2 = 74;
  public static final int Minimo = 24;
  public static final int Liquido = 43;
  public static final int Dero = 5;
  public static final int Temperatura_actual = 23;
  public static final int Menor_igual = 64;
  public static final int Mayor_igual = 65;
  public static final int CaracterEs = 60;
  public static final int Fertsol = 36;
  public static final int Inverna = 4;
  public static final int Signo_Puntuacion = 59;
  public static final int EOF = 0;
  public static final int Numero = 53;
  public static final int Decrementar = 27;
  public static final int Division = 51;
  public static final int Hr = 20;
  public static final int Vaho = 22;
  public static final int error = 1;
  public static final int No = 15;
  public static final int Fertliq = 35;
  public static final int Continuar = 33;
  public static final int Menor_que = 61;
  public static final int Temperatura = 10;
  public static final int Riego = 42;
  public static final int Cordy = 38;
  public static final int Cordx = 37;
  public static final int Identificador = 52;
  public static final int Siempre = 18;
  public static final int Por = 39;
  public static final int Igual_igual = 66;
  public static final int Reservadas = 2;
  public static final int Igual = 63;
  public static final int Detener = 30;
  public static final int Min = 19;
  public static final int Si = 14;
  public static final int Multiplicacion = 50;
  public static final int Luz = 12;
  public static final int Empezar = 41;
}

